parameters:
    octava.job_queue.config.class: Octava\Bundle\JobQueueBundle\Config

services:
    Octava\Bundle\JobQueueBundle\Config: ~

    octava.job_queue.manager:
        class: Octava\Bundle\JobQueueBundle\Manager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Octava\Bundle\JobQueueBundle\Config'

    Octava\Bundle\JobQueueBundle\Admin\JobAdmin:
        arguments:
            - ~
            - JMS\JobQueueBundle\Entity\Job
            - Octava\Bundle\JobQueueBundle\Controller\JobAdminController
        calls:
            - [setTranslationDomain, ['OctavaJobQueueBundle']]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: JobQueue }
        public: true

    Octava\Bundle\JobQueueBundle\Command\RunCommand:
        arguments:
            - '@Octava\Bundle\JobQueueBundle\Config'
        tags:
            - { name: console.command }
