parameters:
    octava.job_queue.config.class: Octava\Bundle\JobQueueBundle\Config

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Octava\Bundle\JobQueueBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Resources}'

    Octava\Bundle\JobQueueBundle\Controller\JobAdminController:
        tags:
            - { name: 'controller.service_arguments' }

    Octava\Bundle\JobQueueBundle\Config: ~

    octava.job_queue.manager:
        class: Octava\Bundle\JobQueueBundle\Manager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Octava\Bundle\JobQueueBundle\Config'

    Octava\Bundle\JobQueueBundle\Admin\JobAdmin:
        tags:
            -
                name: sonata.admin
                code: ~
                model_class: JMS\JobQueueBundle\Entity\Job
                controller: Octava\Bundle\JobQueueBundle\Controller\JobAdminController
                manager_type: orm
                group: admin
                label: JobQueue
                translation_domain: OctavaJobQueueBundle
        public: true

    Octava\Bundle\JobQueueBundle\Command\RunCommand:
        arguments:
            - '@Octava\Bundle\JobQueueBundle\Config'
            - '@doctrine'
            - '@jms_job_queue.job_manager'
            - '@event_dispatcher'
            - '%jms_job_queue.queue_options_defaults%'
            - '%jms_job_queue.queue_options%'
        tags:
            - { name: console.command }
